In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\manav\Downloads\The Titanic dataset.csv")
df

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1297,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,13,S,19-Jul-93
1298,1297,3,0,"Zabour, Miss. Hileni",female,14.5,1,14.4542,C,20-Jul-93
1299,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,7.225,C,21-Jul-93
1300,1299,3,0,"Zakarian, Mr. Ortin",male,27,0,7.225,C,22-Jul-93
1301,1300,3,0,"Zimmerman, Mr. Leo",male,29,0,7.875,S,23-Jul-93

In [6]:
df.head()

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1302 non-null   object
 1   2       1302 non-null   object
 2   3       1302 non-null   object
 3   4       1301 non-null   object
 4   5       1301 non-null   object
 5   6       1045 non-null   object
 6   7       1300 non-null   object
 7   8       1300 non-null   object
 8   9       1296 non-null   object
 9   10      1302 non-null   object
dtypes: object(10)
memory usage: 101.8+ KB

In [9]:
df.describe()

,1,2,3,4,5,6,7,8,9,10
count,1302,1302,1302,1301,1301,1045,1300,1300,1296,1302
unique,1301,4,3,1297,3,98,10,283,4,1301
top,1,3,0,"Connolly, Miss. Kate",male,24,0,13,S,01-Jan-90
freq,2,700,801,2,835,47,781,59,905,2

In [10]:
df.shape

(1302, 10)

In [19]:
df.sort_values('10')

,1,2,3,4,5,6,7,8,9,10
92,91,3,0,"Barbara, Miss. Saiide",female,18,1,14.4542,C,01-Apr-90
457,456,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,89.1042,C,01-Apr-91
823,822,3,1,"Moor, Master. Meier",male,6,1,12.475,S,01-Apr-92
1188,1187,3,0,"Thomas, Mr. John",male,NaN,0,6.4375,C,01-Apr-93
214,213,2,0,"Carter, Rev. Ernest Courtenay",male,54,1,26,S,01-Aug-90
...,...,...,...,...,...,...,...,...,...,...
1248,1247,2,0,"Watson, Mr. Ennis Hastings",male,NaN,0,0,S,31-May-93
305,304,1,0,"Davidson, Mr. Thornton",male,31,1,52,S,31-Oct-90
670,669,3,0,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36,2,12.1833,S,31-Oct-91
1036,1035,3,1,"Roth, Miss. Sarah A",female,NaN,0,8.05,S,31-Oct-92
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date

In [7]:
#rename(), which lets change column names.
df.rename(columns={'Duration':"Time Spent"})

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1297,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,13,S,19-Jul-93
1298,1297,3,0,"Zabour, Miss. Hileni",female,14.5,1,14.4542,C,20-Jul-93
1299,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,7.225,C,21-Jul-93
1300,1299,3,0,"Zakarian, Mr. Ortin",male,27,0,7.225,C,22-Jul-93
1301,1300,3,0,"Zimmerman, Mr. Leo",male,29,0,7.875,S,23-Jul-93